name: Build Docker Image

on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      # 1️⃣ stáhne kód z repa
      - name: Checkout repository
        uses: actions/checkout@v4

      # 2️⃣ nastaví Docker Buildx pro build
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3

      # 3️⃣ build Docker image
      - name: Build Docker image
        run: docker build -t flask-school-app .
